### PR TITLE
Accessly logo ✨

### PR DESCRIPTION
**Pull request by wsmd**
## Why?

Because every gem deserves a logo, and because why not?

## What?

Congrats on shipping the initial release! :tada:

Here's a tiny logo for the gem:

I included png+svg formats.

Nothing too fancy, but it's something... I hope you like it and would love to hear your thoughts!

Once merged you should expect something like this in the README:

screen shot 2018-03-28 at 6 43 18 pm

Let the stickers commence!

### CODE REVIEW

**Comment by armilam** [comment]
Nice! I'm curious - is that in the same typeface as the Lessonly logo?

**Comment by armilam** [comment]
Same colors, for sure.

**Comment by armilam** [comment]
I love this, by the way

**Comment by wsmd** [comment]
>  is that in the same typeface as the Lessonly logo?

Not the lessonly logo itself, but It's the same typeface used for most of the marketing material.

E.g. https://www.lessonly.com/yellowship/

**Comment by armilam** [comment]
Neat!

**Pull request merged**
